### ISSUE TITLE
when run python3 scope_start.py --config-file radio_interactive.conf error happens

### ISSUE THREAD

**Issue by SOANykun** [wineslab/colosseum-scope#3]
ERROR    No nodes found, exiting. Did you start the Colosseum scenario (colosseumcli rf start <scenario-number> -c)? If in batch mode, disable the colosseumcli option in the configuration file

**Comment by SOANykun** [comment]
After I modify "colosseumcli = False" in file radio_interactive.conf still error happens as follow:

ERROR    Interface col0 is not active. Exiting execution

**Comment by SOANykun** [comment]
![image](https://user-images.githubusercontent.com/37335717/194293504-adb3f63a-2b9e-449f-bdda-79ce4ce29253.png)

**Comment by leonardobonati** [comment]
Hi SOANykun,

My suspicion is that you are either trying this in a Colosseum reservation with one node only (in this case, please make a reservation with multiple nodes), or outside the Colosseum environment (in this case, you need to adapt the scripts to use a wired interface that connects your nodes, e.g., an interface to a common switch, since you do not seem to have an interface called `col0`). Also, please note that this is only used for node discovery and you can still run the remaining scripts with the external option.

**Comment by SOANykun** [comment]
Thank you very much, as you said i am outside the Colosseum environment, but I don't know how to enter the coloseum experimental environment can you teach me?

**Comment by SOANykun** [comment]
OK，thank you

**Comment by SOANykun** [comment]
Hi, if I don't have NSF grant number Can I apply for using colosseum?

**Comment by leonardobonati** [comment]
I am not sure, you can try to submit the form anyway.
